### ISSUE TITLE
p value

### ISSUE THREAD

**Issue by houssem-tum** [syrte/ndtest#2]
Hello, 
can you please explain, what is the meaning of p value as output of ks2d2s ? 
Thanks.

**Comment by syrte** [comment]
The target of p-value is to tell if the observed variable (max distance here) follows a given distribution. p-value means the probability of getting a value under this distribution more extreme than the observed one. If you consider the one-tailed case, p-value of x is the survival function sf(x) = 1 - cdf(x). If the p-value of observation is very small, then we can say the observation is unlikely drawn from the assumed distribution.

E.g. assume you get a random number `4`, then it seems unlikely to be drawn from a standard normal distribution N(0, 1) because `norm.sf(4) = 1 - norm.cdf(4) = 3e-5`.

In the 2 samples 2D KD test problem, the exact distribution of the KS statistics (max distance) p(D) is very hard to know, it actually depends on the distribution of the sample itself. We have to make some approximations, here I provide two implementations. One makes use of `kstwobign.sf`, one makes use of bootstrap experiments. bootstrap is more recommended, though it needs much more computations.
